services:
  ourtime_db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ourtime_db
    volumes:
      - db_data:/var/lib/postgresql/data
  ourtime_web:
    build: .
    volumes:
      - ./src:/app
      - bundle:/usr/local/bundle 
    ports:
      - "3000:3000"
    depends_on:
      - ourtime_db
    environment:
      DB_HOST: ourtime_db
      DB_USER: postgres
      DB_PASSWORD: password
      DB_NAME: ourtime_db
      DB_PORT: 5432

volumes:
  db_data:
  bundle:
    driver: local